name: PR

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a test
        run: |
          echo "This workflow was triggered by a ${{ github.event_name }} event."
          echo "Branch: ${{ github.ref }}"